name: OpenCode + Agent-Zero Automated Test

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Run automated test suite
        run: bash scripts/automated_test.sh

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: test_reports/
